In [1]:
#PIAIC AI Batch 4 Q2
#Numpy Assignment
#Roll NO: PIAIC61835
#Name Farooq Aziz

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.19.2


In [4]:
stringArray = np.array(["aaa", "aab", "aca", "abb", "aca"])

In [5]:
'aa' in stringArray

False

In [6]:
'aaa' in stringArray

True

In [7]:
arr = np.array([1, 2, 3, 4, 5])

In [8]:
print(arr)

[1 2 3 4 5]


In [9]:
type(arr)

numpy.ndarray

In [10]:
arr[0]

1

In [11]:
arr[3]

4

In [12]:
arr[1:2]

array([2])

In [13]:
arr[:3]

array([1, 2, 3])

In [14]:
zeroArray=np.zeros(6)

In [15]:
zeroArray

array([0., 0., 0., 0., 0., 0.])

In [16]:
type(zeroArray)

numpy.ndarray

In [17]:
type(zeroArray[4])

numpy.float64

In [18]:
onesArray=np.ones(6)

In [19]:
onesArray

array([1., 1., 1., 1., 1., 1.])

In [20]:
emptyArray=np.empty(8)

In [21]:
emptyArray

array([8.70367085e-313, 0.00000000e+000, 3.62633684e+228, 1.14567609e+243,
       4.32449796e-096, 9.78750380e+199, 6.97843734e+252, 2.65690387e-312])

In [22]:
emptyArray.shape =(2,4)


In [23]:
emptyArray

array([[8.70367085e-313, 0.00000000e+000, 3.62633684e+228,
        1.14567609e+243],
       [4.32449796e-096, 9.78750380e+199, 6.97843734e+252,
        2.65690387e-312]])

In [24]:
x = [2, 3, 4, 5, 6]
nums = np.array([2, 3, 4, 5, 6])
type(nums)

numpy.ndarray

In [25]:
array = np.arange(10)

In [26]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
b = np.arange(12).reshape(4,3)

In [28]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
c = np.arange(30).reshape(2,3,5)  

In [30]:
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [31]:
a = np.array([[1, 2], [3, 4]]) 
a

array([[1, 2],
       [3, 4]])

In [32]:
a = np.array([1, 2, 3,4,5], ndmin = 2) 
a

array([[1, 2, 3, 4, 5]])

In [33]:
a = np.array([1, 2, 3], dtype = complex) 
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [34]:
bool_arr = np.array([1, 0.5, 0, None, 'a', '', True, False], dtype=bool)
bool_arr


array([ True,  True, False, False,  True, False,  True, False])

In [35]:
a = np.array([(1,2,3),(4,5,6)])
a.ndim

2

In [36]:
a = np.array([(1,2,3)])
a.itemsize

4

In [37]:
a = np.array([(1,2,3)])
a.dtype

dtype('int32')

In [38]:
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


In [39]:
a=np.array([(1,2,3,4),(3,4,5,6)])
a[0:,2]

array([3, 5])

In [40]:
a=np.array([(8,9),(10,11),(12,13)])
a[0:2,1]

array([ 9, 11])

In [41]:
a=np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [42]:
a= np.array([1,2,3])
print(a.min())

1


In [43]:
a= np.array([1,2,3])
print(a.max())

3


In [44]:
a= np.array([1,2,3])
print(a.sum())

6


In [45]:
a=np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]


In [46]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)

[[0 0 0]
 [0 0 0]]


In [47]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x*y)

[[ 1  4  9]
 [ 9 16 25]]


In [48]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x/y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [49]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]


In [50]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.hstack((x,y)))

[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [51]:
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]


In [52]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [53]:
thearray = np.logspace(5, 10, num=10, base=10000000.0, dtype=float)
print(thearray)

[1.00000000e+35 7.74263683e+38 5.99484250e+42 4.64158883e+46
 3.59381366e+50 2.78255940e+54 2.15443469e+58 1.66810054e+62
 1.29154967e+66 1.00000000e+70]


In [54]:

print(np.random.rand(3, 2))

[[0.9046788  0.17807214]
 [0.71578014 0.56269103]
 [0.57540785 0.87040939]]


In [55]:
print(np.random.randn(3, 2))

[[ 1.56972502 -1.0597458 ]
 [-0.47720821  1.00310306]
 [-1.11743772  1.29526459]]


In [56]:

print(np.random.randint(2, size=10))
print(np.random.randint(5, size=(2, 4)))

[1 0 0 0 0 1 1 0 1 1]
[[4 1 2 3]
 [0 1 2 0]]


In [57]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [58]:
print(np.diag(np.arange(0, 8, 2)))

[[0 0 0 0]
 [0 2 0 0]
 [0 0 4 0]
 [0 0 0 6]]


In [59]:
print(np.diag(np.diag(np.arange(9).reshape((3,3)))))

[[0 0 0]
 [0 4 0]
 [0 0 8]]


In [60]:
array1d = np.array([1, 2, 3, 4, 5, 6])
print(array1d[0]) 
print(array1d[-1])
print(array1d[3])  
print(array1d[-5])  

1
6
4
2


In [61]:
print(array1d[[0, -1]])

[1 6]


In [62]:
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array3d)
 
print(array3d[0, 0, 0])
print(array3d[0, 0, 1])
print(array3d[0, 0, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3


In [63]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
 
arrayH = np.hstack((array1, array2))
print(arrayH)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [64]:
arrayV = np.vstack((array1, array2))
print(arrayV)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [65]:
arrayC = np.concatenate((array1, array2))
print(arrayC)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [66]:
arrayA = np.append(array1, array2, axis=0)
print(arrayA)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [67]:
arrayA = np.append(array1, array2, axis=1)
print(arrayA)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [68]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
 
print(np.sin(array1))

[[-0.54402111  0.91294525 -0.98803162]
 [ 0.74511316 -0.26237485 -0.30481062]]


In [69]:
print(np.cos(array1))

[[-0.83907153  0.40808206  0.15425145]
 [-0.66693806  0.96496603 -0.95241298]]


In [70]:
print(np.tan(array1))

[[ 0.64836083  2.23716094 -6.4053312 ]
 [-1.11721493 -0.27190061  0.32004039]]


In [71]:
print(np.sqrt(array1))

[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]


In [72]:
print(np.exp(array1))

[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]]


In [73]:
print(np.log10(array1))

[[1.         1.30103    1.47712125]
 [1.60205999 1.69897    1.77815125]]


In [74]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
array2 = np.array([[2, 3, 4], [4, 6, 8]])
array3 = np.array([[-2, 3.5, -4], [4.05, -6, 8]])
print(np.add(array1, array2))

[[12 23 34]
 [44 56 68]]


In [75]:
print(np.power(array1, array2))

[[        100        8000      810000]
 [    2560000 -1554869184 -1686044672]]


In [76]:
print(np.remainder((array2), 5))

[[2 3 4]
 [4 1 3]]


In [77]:
print(np.reciprocal(array3))

[[-0.5         0.28571429 -0.25      ]
 [ 0.24691358 -0.16666667  0.125     ]]


In [78]:
print(np.sign(array3))

[[-1.  1. -1.]
 [ 1. -1.  1.]]


In [79]:

print(np.ceil(array3))

[[-2.  4. -4.]
 [ 5. -6.  8.]]


In [80]:
print(np.round(array3))

[[-2.  4. -4.]
 [ 4. -6.  8.]]


In [81]:
print("Sum of Array: ", np.sum(array1))

Sum of Array:  210


In [82]:
print("Std: ", np.std(array1))

Std:  17.07825127659933


In [83]:
print("Var: ", np.var(array1))

Var:  291.6666666666667


In [84]:
print("Prod Value: ", np.prod(array1))

Prod Value:  720000000


In [85]:
array1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
 
print("Mean Value: ", np.mean(array1))

Mean Value:  50.0
